#if !defined(AFX_ALLIGATORFUNCTION_H__C65FDD1C_81D3_4F6D_A58D_C5E9A06AF9CE__INCLUDED_)
#define AFX_ALLIGATORFUNCTION_H__C65FDD1C_81D3_4F6D_A58D_C5E9A06AF9CE__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CPen1;

/////////////////////////////////////////////////////////////////////////////
// CAlligatorFunction wrapper class

class CAlligatorFunction : public COleDispatchDriver
{
public:
	CAlligatorFunction() {}		// Calls COleDispatchDriver default constructor
	CAlligatorFunction(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CAlligatorFunction(const CAlligatorFunction& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CPen1 GetTeethPen();
	CPen1 GetLipsPen();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_ALLIGATORFUNCTION_H__C65FDD1C_81D3_4F6D_A58D_C5E9A06AF9CE__INCLUDED_)
