#if !defined(AFX_ANIMATIONLIST_H__533019E7_EC00_41F7_9DC0_5A770114722B__INCLUDED_)
#define AFX_ANIMATIONLIST_H__533019E7_EC00_41F7_9DC0_5A770114722B__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CChartAnimations;

/////////////////////////////////////////////////////////////////////////////
// CAnimationList wrapper class

class CAnimationList : public COleDispatchDriver
{
public:
	CAnimationList() {}		// Calls COleDispatchDriver default constructor
	CAnimationList(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CAnimationList(const CAnimationList& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long Add(long AnimationClass);
	CChartAnimations GetItems(long Index);
	VARIANT GetControlDefault(long Index);
	void Clear();
	void Delete(long Index);
	long GetCount();
	void SetActive(BOOL bNewValue);
	void Exchange(long Index1, long Index2);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_ANIMATIONLIST_H__533019E7_EC00_41F7_9DC0_5A770114722B__INCLUDED_)
