#if !defined(AFX_ANIMATIONS_H__C4A69C5D_A6CA_41DE_807A_61F1A8090224__INCLUDED_)
#define AFX_ANIMATIONS_H__C4A69C5D_A6CA_41DE_807A_61F1A8090224__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CTeeAnimation;

/////////////////////////////////////////////////////////////////////////////
// CAnimations wrapper class

class CAnimations : public COleDispatchDriver
{
public:
	CAnimations() {}		// Calls COleDispatchDriver default constructor
	CAnimations(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CAnimations(const CAnimations& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CTeeAnimation GetAnimation(long AIndex);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_ANIMATIONS_H__C4A69C5D_A6CA_41DE_807A_61F1A8090224__INCLUDED_)
