#if !defined(AFX_ARROWTOOL_H__3AD7213E_F21B_4008_9281_6FCC6BE78770__INCLUDED_)
#define AFX_ARROWTOOL_H__3AD7213E_F21B_4008_9281_6FCC6BE78770__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CTeePoint2D;
class CGradient;

/////////////////////////////////////////////////////////////////////////////
// CArrowTool wrapper class

class CArrowTool : public COleDispatchDriver
{
public:
	CArrowTool() {}		// Calls COleDispatchDriver default constructor
	CArrowTool(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CArrowTool(const CArrowTool& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	double GetAngle();
	void SetAngle(double newValue);
	BOOL GetDraw2D();
	void SetDraw2D(BOOL bNewValue);
	BOOL GetFilled();
	void SetFilled(BOOL bNewValue);
	CTeePoint2D GetFromPoint();
	CGradient GetGradient();
	long GetHeight();
	void SetHeight(long nNewValue);
	double GetPercent();
	void SetPercent(double newValue);
	BOOL GetRotateGradient();
	void SetRotateGradient(BOOL bNewValue);
	CTeePoint2D GetToPoint();
	long GetTransparency();
	void SetTransparency(long nNewValue);
	long GetWidth();
	void SetWidth(long nNewValue);
	long GetZ();
	void SetZ(long nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_ARROWTOOL_H__3AD7213E_F21B_4008_9281_6FCC6BE78770__INCLUDED_)
