#if !defined(AFX_ATRFUNCTION_H__7F68A3FE_1C8D_422A_9CD9_B2C8858DEC11__INCLUDED_)
#define AFX_ATRFUNCTION_H__7F68A3FE_1C8D_422A_9CD9_B2C8858DEC11__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CATRFunction wrapper class

class CATRFunction : public COleDispatchDriver
{
public:
	CATRFunction() {}		// Calls COleDispatchDriver default constructor
	CATRFunction(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CATRFunction(const CATRFunction& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	BOOL GetIncludeNulls();
	void SetIncludeNulls(BOOL bNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_ATRFUNCTION_H__7F68A3FE_1C8D_422A_9CD9_B2C8858DEC11__INCLUDED_)
