#if !defined(AFX_AUTOMATICTEXT_H__DA2D4BE0_5221_4CF6_A15E_6589554B4377__INCLUDED_)
#define AFX_AUTOMATICTEXT_H__DA2D4BE0_5221_4CF6_A15E_6589554B4377__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CAutomaticText wrapper class

class CAutomaticText : public COleDispatchDriver
{
public:
	CAutomaticText() {}		// Calls COleDispatchDriver default constructor
	CAutomaticText(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CAutomaticText(const CAutomaticText& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	BOOL GetHide();
	void SetHide(BOOL bNewValue);
	BOOL GetMove();
	void SetMove(BOOL bNewValue);
	BOOL GetResize();
	void SetResize(BOOL bNewValue);
	BOOL GetRotate();
	void SetRotate(BOOL bNewValue);
	BOOL GetTrim();
	void SetTrim(BOOL bNewValue);
	BOOL GetWrap();
	void SetWrap(BOOL bNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_AUTOMATICTEXT_H__DA2D4BE0_5221_4CF6_A15E_6589554B4377__INCLUDED_)
