#if !defined(AFX_AXISLABELSITEM_H__C0A73657_1A15_4583_A413_B6B75ADAEEC6__INCLUDED_)
#define AFX_AXISLABELSITEM_H__C0A73657_1A15_4583_A413_B6B75ADAEEC6__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CCustomTextShape;

/////////////////////////////////////////////////////////////////////////////
// CAxisLabelsItem wrapper class

class CAxisLabelsItem : public COleDispatchDriver
{
public:
	CAxisLabelsItem() {}		// Calls COleDispatchDriver default constructor
	CAxisLabelsItem(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CAxisLabelsItem(const CAxisLabelsItem& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	double GetValue();
	void SetValue(double newValue);
	CString GetText();
	void SetText(LPCTSTR lpszNewValue);
	long GetLabelPos();
	void SetLabelPos(long nNewValue);
	CCustomTextShape GetFormat();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_AXISLABELSITEM_H__C0A73657_1A15_4583_A413_B6B75ADAEEC6__INCLUDED_)
