#if !defined(AFX_AXISBREAK_H__C27FB1DE_1947_4B1B_89D8_2419D1104C96__INCLUDED_)
#define AFX_AXISBREAK_H__C27FB1DE_1947_4B1B_89D8_2419D1104C96__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CAxisBreak wrapper class

class CAxisBreak : public COleDispatchDriver
{
public:
	CAxisBreak() {}		// Calls COleDispatchDriver default constructor
	CAxisBreak(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CAxisBreak(const CAxisBreak& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	BOOL GetEnabled();
	void SetEnabled(BOOL bNewValue);
	double GetEndValue();
	void SetEndValue(double newValue);
	double GetStartValue();
	void SetStartValue(double newValue);
	long GetAxisBreakStyle();
	void SetAxisBreakStyle(long nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_AXISBREAK_H__C27FB1DE_1947_4B1B_89D8_2419D1104C96__INCLUDED_)
