#if !defined(AFX_AXISBREAKS_H__F0E39CBD_0E4E_45F7_86E4_E066BDB49575__INCLUDED_)
#define AFX_AXISBREAKS_H__F0E39CBD_0E4E_45F7_86E4_E066BDB49575__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CAxisBreak;

/////////////////////////////////////////////////////////////////////////////
// CAxisBreaks wrapper class

class CAxisBreaks : public COleDispatchDriver
{
public:
	CAxisBreaks() {}		// Calls COleDispatchDriver default constructor
	CAxisBreaks(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CAxisBreaks(const CAxisBreaks& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CAxisBreak GetItem(long Index);
	long Add(double AStart, double AEnd);
	long GetCount();
	void Clear();
	void Delete(long AIndex);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_AXISBREAKS_H__F0E39CBD_0E4E_45F7_86E4_E066BDB49575__INCLUDED_)
