#if !defined(AFX_CHARTANIMATIONS_H__EE93977B_E194_43D3_8A0E_F792C4DACE0E__INCLUDED_)
#define AFX_CHARTANIMATIONS_H__EE93977B_E194_43D3_8A0E_F792C4DACE0E__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CExpandAnimation;
class CTransformAnimation;

/////////////////////////////////////////////////////////////////////////////
// CChartAnimations wrapper class

class CChartAnimations : public COleDispatchDriver
{
public:
	CChartAnimations() {}		// Calls COleDispatchDriver default constructor
	CChartAnimations(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CChartAnimations(const CChartAnimations& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CExpandAnimation GetAsExpand();
	CTransformAnimation GetAsTransformation();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CHARTANIMATIONS_H__EE93977B_E194_43D3_8A0E_F792C4DACE0E__INCLUDED_)
