// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "chartanimations.h"

// Dispatch interfaces referenced by this interface
#include "ExpandAnimation.h"
#include "TransformAnimation.h"


/////////////////////////////////////////////////////////////////////////////
// CChartAnimations properties

/////////////////////////////////////////////////////////////////////////////
// CChartAnimations operations

CExpandAnimation CChartAnimations::GetAsExpand()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x12d, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CExpandAnimation(pDispatch);
}

CTransformAnimation CChartAnimations::GetAsTransformation()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0xc9, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CTransformAnimation(pDispatch);
}
