#if !defined(AFX_CHARTAXISPEN_H__333A5AC0_A487_4702_BD48_677261175EED__INCLUDED_)
#define AFX_CHARTAXISPEN_H__333A5AC0_A487_4702_BD48_677261175EED__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CBrush1;

/////////////////////////////////////////////////////////////////////////////
// CChartAxisPen wrapper class

class CChartAxisPen : public COleDispatchDriver
{
public:
	CChartAxisPen() {}		// Calls COleDispatchDriver default constructor
	CChartAxisPen(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CChartAxisPen(const CChartAxisPen& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	unsigned long GetColor();
	void SetColor(unsigned long newValue);
	long GetWidth();
	void SetWidth(long nNewValue);
	long GetStyle();
	void SetStyle(long nNewValue);
	BOOL GetVisible();
	void SetVisible(BOOL bNewValue);
	long GetEndStyle();
	void SetEndStyle(long nNewValue);
	BOOL ShowEditor(BOOL HideColor, LPCTSTR Title, long OwnerChart);
	long GetSmallSpace();
	void SetSmallSpace(long nNewValue);
	long GetMode();
	void SetMode(long nNewValue);
	void Show();
	void Hide();
	CBrush1 GetFill();
	long GetJoinStyle();
	void SetJoinStyle(long nNewValue);
	BOOL GetSmallDots();
	void SetSmallDots(BOOL bNewValue);
	long GetLineMode();
	void SetLineMode(long nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CHARTAXISPEN_H__333A5AC0_A487_4702_BD48_677261175EED__INCLUDED_)
