#if !defined(AFX_CHARTHIDDENPEN_H__37EB1CFB_65E9_4019_B1AE_D8F55D5AB543__INCLUDED_)
#define AFX_CHARTHIDDENPEN_H__37EB1CFB_65E9_4019_B1AE_D8F55D5AB543__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CBrush1;

/////////////////////////////////////////////////////////////////////////////
// CChartHiddenPen wrapper class

class CChartHiddenPen : public COleDispatchDriver
{
public:
	CChartHiddenPen() {}		// Calls COleDispatchDriver default constructor
	CChartHiddenPen(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CChartHiddenPen(const CChartHiddenPen& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	unsigned long GetColor();
	void SetColor(unsigned long newValue);
	long GetWidth();
	void SetWidth(long nNewValue);
	long GetStyle();
	void SetStyle(long nNewValue);
	BOOL GetVisible();
	void SetVisible(BOOL bNewValue);
	long GetEndStyle();
	void SetEndStyle(long nNewValue);
	BOOL ShowEditor(BOOL HideColor, LPCTSTR Title, long OwnerChart);
	long GetSmallSpace();
	void SetSmallSpace(long nNewValue);
	long GetMode();
	void SetMode(long nNewValue);
	void Show();
	void Hide();
	CBrush1 GetFill();
	long GetJoinStyle();
	void SetJoinStyle(long nNewValue);
	BOOL GetSmallDots();
	void SetSmallDots(BOOL bNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CHARTHIDDENPEN_H__37EB1CFB_65E9_4019_B1AE_D8F55D5AB543__INCLUDED_)
