#if !defined(AFX_CIRCULARFRAME_H__22B26A35_2131_418A_A3D4_C6D4DCC9E267__INCLUDED_)
#define AFX_CIRCULARFRAME_H__22B26A35_2131_418A_A3D4_C6D4DCC9E267__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CBrush1;
class CFrameBrush;
class CTeeShadow;
class CTeeEmboss;

/////////////////////////////////////////////////////////////////////////////
// CCircularFrame wrapper class

class CCircularFrame : public COleDispatchDriver
{
public:
	CCircularFrame() {}		// Calls COleDispatchDriver default constructor
	CCircularFrame(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CCircularFrame(const CCircularFrame& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CBrush1 GetBrush();
	BOOL GetCircled();
	void SetCircled(BOOL bNewValue);
	CFrameBrush GetInnerBrush();
	CFrameBrush GetMiddleBrush();
	CFrameBrush GetOuterBrush();
	CTeeShadow GetShadow();
	BOOL GetVisible();
	void SetVisible(BOOL bNewValue);
	long GetWidth();
	void SetWidth(long nNewValue);
	CTeeEmboss GetEmboss();
	long GetRotationAngle();
	void SetRotationAngle(long nNewValue);
	long GetTotalAngle();
	void SetTotalAngle(long nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CIRCULARFRAME_H__22B26A35_2131_418A_A3D4_C6D4DCC9E267__INCLUDED_)
