#if !defined(AFX_CLOCKHAND_H__08BB9DBF_6074_4A66_9130_3555AC68D8E7__INCLUDED_)
#define AFX_CLOCKHAND_H__08BB9DBF_6074_4A66_9130_3555AC68D8E7__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CBrush1;
class CPen1;

/////////////////////////////////////////////////////////////////////////////
// CClockHand wrapper class

class CClockHand : public COleDispatchDriver
{
public:
	CClockHand() {}		// Calls COleDispatchDriver default constructor
	CClockHand(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CClockHand(const CClockHand& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CBrush1 GetBrush();
	CPen1 GetFrame();
	CPen1 GetPen();
	BOOL GetVisible();
	void SetVisible(BOOL bNewValue);
	long GetArrow();
	void SetArrow(long nNewValue);
	long GetHeight();
	void SetHeight(long nNewValue);
	long GetSize();
	void SetSize(long nNewValue);
	long GetWidth();
	void SetWidth(long nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CLOCKHAND_H__08BB9DBF_6074_4A66_9130_3555AC68D8E7__INCLUDED_)
