#if !defined(AFX_CUSTOMAXES_H__D937B64E_7AD9_4E16_A5A6_DB9928680CEC__INCLUDED_)
#define AFX_CUSTOMAXES_H__D937B64E_7AD9_4E16_A5A6_DB9928680CEC__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CAxis;

/////////////////////////////////////////////////////////////////////////////
// CCustomAxes wrapper class

class CCustomAxes : public COleDispatchDriver
{
public:
	CCustomAxes() {}		// Calls COleDispatchDriver default constructor
	CCustomAxes(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CCustomAxes(const CCustomAxes& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long Add();
	CAxis GetItems(long AIndex);
	void ResetScales(long AIndex);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CUSTOMAXES_H__D937B64E_7AD9_4E16_A5A6_DB9928680CEC__INCLUDED_)
