#if !defined(AFX_DOWNSAMPLINGFUNCTION_H__07B563BF_2D6D_4185_A09B_74ED0D4A3FA1__INCLUDED_)
#define AFX_DOWNSAMPLINGFUNCTION_H__07B563BF_2D6D_4185_A09B_74ED0D4A3FA1__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CDownSamplingFunction wrapper class

class CDownSamplingFunction : public COleDispatchDriver
{
public:
	CDownSamplingFunction() {}		// Calls COleDispatchDriver default constructor
	CDownSamplingFunction(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CDownSamplingFunction(const CDownSamplingFunction& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetDownSampleMethod();
	void SetDownSampleMethod(long nNewValue);
	long GetTolerance();
	void SetTolerance(long nNewValue);
	long GetReducedSize();
	long GetDisplayedPointCount();
	void SetDisplayedPointCount(long nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_DOWNSAMPLINGFUNCTION_H__07B563BF_2D6D_4185_A09B_74ED0D4A3FA1__INCLUDED_)
