#if !defined(AFX_ERRORS3D_H__49EEAB64_F0BD_453F_9530_9BDE00E0BCD5__INCLUDED_)
#define AFX_ERRORS3D_H__49EEAB64_F0BD_453F_9530_9BDE00E0BCD5__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CValueList;
class CErrors3DFormat;

/////////////////////////////////////////////////////////////////////////////
// CErrors3D wrapper class

class CErrors3D : public COleDispatchDriver
{
public:
	CErrors3D() {}		// Calls COleDispatchDriver default constructor
	CErrors3D(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CErrors3D(const CErrors3D& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CValueList GetLeft();
	CValueList GetRight();
	CValueList GetTop();
	CValueList GetBottom();
	BOOL GetSeriesColor();
	void SetSeriesColor(BOOL bNewValue);
	long GetSize();
	void SetSize(long nNewValue);
	long GetSizeUnits();
	void SetSizeUnits(long nNewValue);
	CErrors3DFormat GetFormat();
	CValueList GetFront();
	CValueList GetBack();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_ERRORS3D_H__49EEAB64_F0BD_453F_9530_9BDE00E0BCD5__INCLUDED_)
