#if !defined(AFX_ERRORPOINT3DSERIES_H__785E8B0D_92FC_441A_B8B7_B69738668535__INCLUDED_)
#define AFX_ERRORPOINT3DSERIES_H__785E8B0D_92FC_441A_B8B7_B69738668535__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CValueList;
class CBrush1;
class CPen1;
class CPointer;
class CErrors3D;

/////////////////////////////////////////////////////////////////////////////
// CErrorPoint3DSeries wrapper class

class CErrorPoint3DSeries : public COleDispatchDriver
{
public:
	CErrorPoint3DSeries() {}		// Calls COleDispatchDriver default constructor
	CErrorPoint3DSeries(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CErrorPoint3DSeries(const CErrorPoint3DSeries& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long AddXYZ(double AX, double AY, double AZ, LPCTSTR AXLabel, unsigned long Value);
	double MaxZValue();
	double MinZValue();
	long GetTimesZOrder();
	void SetTimesZOrder(long nNewValue);
	CValueList GetZValues();
	double GetZValue(long Index);
	void SetZValue(long Index, double newValue);
	CBrush1 GetBrush();
	CPen1 GetPen();
	void AddArrayXYZ(const VARIANT& XArray, const VARIANT& YArray, const VARIANT& ZArray);
	void AddArrayGrid(long NumX, long NumZ, const VARIANT& XZArray);
	long CalcZPos(long ValueIndex);
	void AddArrayXYZColor(const VARIANT& XArray, const VARIANT& YArray, const VARIANT& ZArray, const VARIANT& Colors);
	double GetDepthSize();
	void SetDepthSize(double newValue);
	CPointer GetPointer();
	CPen1 GetLinePen();
	CPen1 GetBaseLine();
	long GetLineTransparency();
	void SetLineTransparency(long nNewValue);
	long Add(double AX, double AY, double AZ, double ALeft, double ARight, double ATop, double ABottom, double AFront, double ABack, LPCTSTR AXLabel, unsigned long Value);
	CErrors3D GetErrors();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_ERRORPOINT3DSERIES_H__785E8B0D_92FC_441A_B8B7_B69738668535__INCLUDED_)
