#if !defined(AFX_ERRORSFORMAT_H__0AD27F68_6705_43D1_B6F1_44A160944715__INCLUDED_)
#define AFX_ERRORSFORMAT_H__0AD27F68_6705_43D1_B6F1_44A160944715__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CPen1;

/////////////////////////////////////////////////////////////////////////////
// CErrorsFormat wrapper class

class CErrorsFormat : public COleDispatchDriver
{
public:
	CErrorsFormat() {}		// Calls COleDispatchDriver default constructor
	CErrorsFormat(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CErrorsFormat(const CErrorsFormat& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CPen1 GetLeft();
	CPen1 GetRight();
	CPen1 GetTop();
	CPen1 GetBottom();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_ERRORSFORMAT_H__0AD27F68_6705_43D1_B6F1_44A160944715__INCLUDED_)
