#if !defined(AFX_EXPANDANIMATION_H__92338418_2EFA_4549_8603_AB2B37FF8545__INCLUDED_)
#define AFX_EXPANDANIMATION_H__92338418_2EFA_4549_8603_AB2B37FF8545__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CAnimations;
class CTeeAnimate;

/////////////////////////////////////////////////////////////////////////////
// CExpandAnimation wrapper class

class CExpandAnimation : public COleDispatchDriver
{
public:
	CExpandAnimation() {}		// Calls COleDispatchDriver default constructor
	CExpandAnimation(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CExpandAnimation(const CExpandAnimation& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetSpeed();
	void SetSpeed(long nNewValue);
	CAnimations GetAnimations();
	CTeeAnimate GetAnimate();
	BOOL GetLoop();
	void SetLoop(BOOL bNewValue);
	long GetSizeBy();
	void SetSizeBy(long nNewValue);
	long GetTarget();
	void SetTarget(long nNewValue);
	long GetTrigger();
	void SetTrigger(long nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_EXPANDANIMATION_H__92338418_2EFA_4549_8603_AB2B37FF8545__INCLUDED_)
