#if !defined(AFX_EXPORT_H__F9E6DD37_E86D_40D2_A3E7_B4B69DB45180__INCLUDED_)
#define AFX_EXPORT_H__F9E6DD37_E86D_40D2_A3E7_B4B69DB45180__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CJPEGExport;
class CPNGExport;
class CGIFExport;
class CBMPExport;
class CPCXExport;
class CMetafileExport;
class CNativeExport;
class CXMLExport;
class CXLSExport;
class CHTMLExport;
class CTextExport;
class CPDFExport;
class CEPSExport;
class CSVGExport;
class CXAMLExport;
class CFlexExport;
class CJavaScriptExport;
class CJSONExport;
class CODSExport;

/////////////////////////////////////////////////////////////////////////////
// CExport wrapper class

class CExport : public COleDispatchDriver
{
public:
	CExport() {}		// Calls COleDispatchDriver default constructor
	CExport(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CExport(const CExport& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	void CopyToClipboardBitmap();
	void CopyToClipboardMetafile(BOOL Enhanced);
	void SaveToBitmapFile(LPCTSTR FileName, long DPI);
	void SaveToFile(LPCTSTR FileName);
	void SaveToJPEGFile(LPCTSTR FileName, BOOL Gray, long Performance, long Quality, long Width, long Height, long DPI);
	void SaveToMetafile(LPCTSTR FileName);
	void SaveToMetafileEnh(LPCTSTR FileName);
	void ShowExport();
	CString SaveChartDialog();
	void ConvertTeeFileToText(LPCTSTR InputFile, LPCTSTR OutputFile);
	VARIANT Stream(long StreamType);
	CJPEGExport GetAsJPEG();
	CPNGExport GetAsPNG();
	CGIFExport GetAsGIF();
	CBMPExport GetAsBMP();
	CPCXExport GetAsPCX();
	CMetafileExport GetAsMetafile();
	CNativeExport GetAsNative();
	CXMLExport GetAsXML();
	CXLSExport GetAsXLS();
	CHTMLExport GetAsHTML();
	CTextExport GetAsText();
	void EmailFile(LPCTSTR FileName, LPCTSTR Subject);
	CPDFExport GetAsPDF();
	CEPSExport GetAsEPS();
	CSVGExport GetAsSVG();
	CString GetLabelHeader();
	void SetLabelHeader(LPCTSTR lpszNewValue);
	CXAMLExport GetAsXAML();
	void SaveToXMLFile(LPCTSTR FileName, BOOL IncludeData, BOOL XMLHeader);
	VARIANT SaveToXMLStream(BOOL IncludeData, BOOL XMLHeader);
	CFlexExport GetAsFlex();
	CJavaScriptExport GetAsJavaScript();
	CJSONExport GetAsJSON();
	CODSExport GetAsOpenDocument();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_EXPORT_H__F9E6DD37_E86D_40D2_A3E7_B4B69DB45180__INCLUDED_)
