#if !defined(AFX_GAUGERANGE_H__8E886AF5_2929_416E_9103_EAC93C0DE832__INCLUDED_)
#define AFX_GAUGERANGE_H__8E886AF5_2929_416E_9103_EAC93C0DE832__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CGaugePointerRange;

/////////////////////////////////////////////////////////////////////////////
// CGaugeRange wrapper class

class CGaugeRange : public COleDispatchDriver
{
public:
	CGaugeRange() {}		// Calls COleDispatchDriver default constructor
	CGaugeRange(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CGaugeRange(const CGaugeRange& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	double GetEndValue();
	void SetEndValue(double newValue);
	double GetStartValue();
	void SetStartValue(double newValue);
	CGaugePointerRange GetFormat();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_GAUGERANGE_H__8E886AF5_2929_416E_9103_EAC93C0DE832__INCLUDED_)
