#if !defined(AFX_GAUGEHANDITEM_H__2D6A32CA_5D93_413C_B214_00651BE7EE2C__INCLUDED_)
#define AFX_GAUGEHANDITEM_H__2D6A32CA_5D93_413C_B214_00651BE7EE2C__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CGaugeHand;

/////////////////////////////////////////////////////////////////////////////
// CGaugeHandItem wrapper class

class CGaugeHandItem : public COleDispatchDriver
{
public:
	CGaugeHandItem() {}		// Calls COleDispatchDriver default constructor
	CGaugeHandItem(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CGaugeHandItem(const CGaugeHandItem& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CGaugeHand GetFormat();
	double GetValue();
	void SetValue(double newValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_GAUGEHANDITEM_H__2D6A32CA_5D93_413C_B214_00651BE7EE2C__INCLUDED_)
