#if !defined(AFX_GAUGEHANDS_H__2274784A_2775_4D67_A37D_647B862AAC20__INCLUDED_)
#define AFX_GAUGEHANDS_H__2274784A_2775_4D67_A37D_647B862AAC20__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CGaugeHandItem;

/////////////////////////////////////////////////////////////////////////////
// CGaugeHands wrapper class

class CGaugeHands : public COleDispatchDriver
{
public:
	CGaugeHands() {}		// Calls COleDispatchDriver default constructor
	CGaugeHands(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CGaugeHands(const CGaugeHands& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CGaugeHandItem GetItems(long AIndex);
	long Add(double AValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_GAUGEHANDS_H__2274784A_2775_4D67_A37D_647B862AAC20__INCLUDED_)
