#if !defined(AFX_GAUGERANGES_H__208B9BA2_C0FB_4C7C_BDCF_664CA71A06A5__INCLUDED_)
#define AFX_GAUGERANGES_H__208B9BA2_C0FB_4C7C_BDCF_664CA71A06A5__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CGaugeRange;

/////////////////////////////////////////////////////////////////////////////
// CGaugeRanges wrapper class

class CGaugeRanges : public COleDispatchDriver
{
public:
	CGaugeRanges() {}		// Calls COleDispatchDriver default constructor
	CGaugeRanges(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CGaugeRanges(const CGaugeRanges& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CGaugeRange GetItems(long Index);
	long Add(double StartValue, double EndValue, unsigned long Color);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_GAUGERANGES_H__208B9BA2_C0FB_4C7C_BDCF_664CA71A06A5__INCLUDED_)
