#if !defined(AFX_HIERARCHICALCLUSTERING_H__43389482_1D9E_4B8B_8A38_B6209AC05CE5__INCLUDED_)
#define AFX_HIERARCHICALCLUSTERING_H__43389482_1D9E_4B8B_8A38_B6209AC05CE5__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CHierarchicalClustering wrapper class

class CHierarchicalClustering : public COleDispatchDriver
{
public:
	CHierarchicalClustering() {}		// Calls COleDispatchDriver default constructor
	CHierarchicalClustering(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CHierarchicalClustering(const CHierarchicalClustering& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetLinkage();
	void SetLinkage(long nNewValue);
	long GetNumClusters();
	void SetNumClusters(long nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_HIERARCHICALCLUSTERING_H__43389482_1D9E_4B8B_8A38_B6209AC05CE5__INCLUDED_)
