#if !defined(AFX_JAVASCRIPTEXPORT_H__9459854A_D7C0_477A_A6FB_C6DFC74FED47__INCLUDED_)
#define AFX_JAVASCRIPTEXPORT_H__9459854A_D7C0_477A_A6FB_C6DFC74FED47__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CStrings;

/////////////////////////////////////////////////////////////////////////////
// CJavaScriptExport wrapper class

class CJavaScriptExport : public COleDispatchDriver
{
public:
	CJavaScriptExport() {}		// Calls COleDispatchDriver default constructor
	CJavaScriptExport(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CJavaScriptExport(const CJavaScriptExport& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetWidth();
	void SetWidth(long nNewValue);
	long GetHeight();
	void SetHeight(long nNewValue);
	void SaveToFile(LPCTSTR FileName);
	VARIANT SaveToStream();
	CString GetSourceScriptPath();
	void SetSourceScriptPath(LPCTSTR lpszNewValue);
	CString GetChartName();
	void SetChartName(LPCTSTR lpszNewValue);
	CString GetCanvasName();
	void SetCanvasName(LPCTSTR lpszNewValue);
	BOOL GetDoFullPage();
	void SetDoFullPage(BOOL bNewValue);
	void SaveToHTML5File(LPCTSTR FileName, long AWidth, long AHeight);
	CStrings GetCustomCode();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_JAVASCRIPTEXPORT_H__9459854A_D7C0_477A_A6FB_C6DFC74FED47__INCLUDED_)
