#if !defined(AFX_JSONEXPORT_H__4D4D2F38_EAEC_48CA_BA3E_A8BFDD78BB3F__INCLUDED_)
#define AFX_JSONEXPORT_H__4D4D2F38_EAEC_48CA_BA3E_A8BFDD78BB3F__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CJSONExport wrapper class

class CJSONExport : public COleDispatchDriver
{
public:
	CJSONExport() {}		// Calls COleDispatchDriver default constructor
	CJSONExport(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CJSONExport(const CJSONExport& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	BOOL GetIncludeHeader();
	void SetIncludeHeader(BOOL bNewValue);
	BOOL GetIncludeLabels();
	void SetIncludeLabels(BOOL bNewValue);
	BOOL GetIncludeIndex();
	void SetIncludeIndex(BOOL bNewValue);
	VARIANT GetSeries();
	void SetSeries(const VARIANT& newValue);
	void SaveToFile(LPCTSTR FileName);
	VARIANT SaveToStream();
	CString AsString();
	BOOL GetIncludeColors();
	void SetIncludeColors(BOOL bNewValue);
	BOOL GetUseSeriesFormat();
	void SetUseSeriesFormat(BOOL bNewValue);
	CString GetValueFormat();
	void SetValueFormat(LPCTSTR lpszNewValue);
	long GetEncoding();
	void SetEncoding(long nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_JSONEXPORT_H__4D4D2F38_EAEC_48CA_BA3E_A8BFDD78BB3F__INCLUDED_)
