#if !defined(AFX_KMEANSCLUSTERING_H__C2EFAF88_C852_440F_A3CF_F7CA1307E45F__INCLUDED_)
#define AFX_KMEANSCLUSTERING_H__C2EFAF88_C852_440F_A3CF_F7CA1307E45F__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CKMeansClustering wrapper class

class CKMeansClustering : public COleDispatchDriver
{
public:
	CKMeansClustering() {}		// Calls COleDispatchDriver default constructor
	CKMeansClustering(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CKMeansClustering(const CKMeansClustering& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetLinkage();
	void SetLinkage(long nNewValue);
	long GetNumClusters();
	void SetNumClusters(long nNewValue);
	long GetMaxIterations();
	void SetMaxIterations(long nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_KMEANSCLUSTERING_H__C2EFAF88_C852_440F_A3CF_F7CA1307E45F__INCLUDED_)
