#if !defined(AFX_LIGHTFILTER_H__204CF800_6E4A_4E8B_B9D1_A729A6D05363__INCLUDED_)
#define AFX_LIGHTFILTER_H__204CF800_6E4A_4E8B_B9D1_A729A6D05363__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CLightFilter wrapper class

class CLightFilter : public COleDispatchDriver
{
public:
	CLightFilter() {}		// Calls COleDispatchDriver default constructor
	CLightFilter(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CLightFilter(const CLightFilter& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetFactor();
	void SetFactor(long nNewValue);
	long GetLeft();
	void SetLeft(long nNewValue);
	long GetStyle();
	void SetStyle(long nNewValue);
	long GetTop();
	void SetTop(long nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_LIGHTFILTER_H__204CF800_6E4A_4E8B_B9D1_A729A6D05363__INCLUDED_)
