#if !defined(AFX_MAPMARKS_H__D52FAA8C_4EEA_4B75_A2F0_91F41B6C4EB4__INCLUDED_)
#define AFX_MAPMARKS_H__D52FAA8C_4EEA_4B75_A2F0_91F41B6C4EB4__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CMapMarks wrapper class

class CMapMarks : public COleDispatchDriver
{
public:
	CMapMarks() {}		// Calls COleDispatchDriver default constructor
	CMapMarks(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CMapMarks(const CMapMarks& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	BOOL GetAutoSize();
	void SetAutoSize(BOOL bNewValue);
	BOOL GetCentroid();
	void SetCentroid(BOOL bNewValue);
	long GetTextStyle();
	void SetTextStyle(long nNewValue);
	BOOL GetUpperCase();
	void SetUpperCase(BOOL bNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_MAPMARKS_H__D52FAA8C_4EEA_4B75_A2F0_91F41B6C4EB4__INCLUDED_)
