#if !defined(AFX_MARKSTAIL_H__998290AE_BEAF_49EF_819A_79A425AB3034__INCLUDED_)
#define AFX_MARKSTAIL_H__998290AE_BEAF_49EF_819A_79A425AB3034__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CTeePoint2D;

/////////////////////////////////////////////////////////////////////////////
// CMarksTail wrapper class

class CMarksTail : public COleDispatchDriver
{
public:
	CMarksTail() {}		// Calls COleDispatchDriver default constructor
	CMarksTail(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CMarksTail(const CMarksTail& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	BOOL GetAutoAlign();
	void SetAutoAlign(BOOL bNewValue);
	long GetMargin();
	void SetMargin(long nNewValue);
	BOOL GetVisible();
	void SetVisible(BOOL bNewValue);
	long GetWidth();
	void SetWidth(long nNewValue);
	BOOL GetCustomPoint();
	void SetCustomPoint(BOOL bNewValue);
	CTeePoint2D GetCustomPointPos();
	long GetHeight();
	void SetHeight(long nNewValue);
	long GetAlign();
	void SetAlign(long nNewValue);
	long GetEdge();
	void SetEdge(long nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_MARKSTAIL_H__998290AE_BEAF_49EF_819A_79A425AB3034__INCLUDED_)
