#if !defined(AFX_MONEYFLOWFUNCTION_H__748BE40B_0E8F_4F69_A7D3_568384A73C1A__INCLUDED_)
#define AFX_MONEYFLOWFUNCTION_H__748BE40B_0E8F_4F69_A7D3_568384A73C1A__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CPen1;

/////////////////////////////////////////////////////////////////////////////
// CMoneyFlowFunction wrapper class

class CMoneyFlowFunction : public COleDispatchDriver
{
public:
	CMoneyFlowFunction() {}		// Calls COleDispatchDriver default constructor
	CMoneyFlowFunction(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CMoneyFlowFunction(const CMoneyFlowFunction& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	BOOL GetAccumulate();
	void SetAccumulate(BOOL bNewValue);
	VARIANT GetVolume();
	void SetVolume(const VARIANT& newValue);
	CPen1 GetHistogramPen();
	CPen1 GetAreaPen();
	long GetCMFStyle();
	void SetCMFStyle(long nNewValue);
	unsigned long GetUpColor();
	void SetUpColor(unsigned long newValue);
	unsigned long GetDownColor();
	void SetDownColor(unsigned long newValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_MONEYFLOWFUNCTION_H__748BE40B_0E8F_4F69_A7D3_568384A73C1A__INCLUDED_)
