#if !defined(AFX_ODSEXPORT_H__1401FD6C_8323_470E_B8CB_5EC6686C8C1A__INCLUDED_)
#define AFX_ODSEXPORT_H__1401FD6C_8323_470E_B8CB_5EC6686C8C1A__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CODSExport wrapper class

class CODSExport : public COleDispatchDriver
{
public:
	CODSExport() {}		// Calls COleDispatchDriver default constructor
	CODSExport(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CODSExport(const CODSExport& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	BOOL GetIncludeHeader();
	void SetIncludeHeader(BOOL bNewValue);
	BOOL GetIncludeLabels();
	void SetIncludeLabels(BOOL bNewValue);
	BOOL GetIncludeIndex();
	void SetIncludeIndex(BOOL bNewValue);
	VARIANT GetSeries();
	void SetSeries(const VARIANT& newValue);
	void SaveToFile(LPCTSTR FileName);
	VARIANT SaveToStream();
	CString AsString();
	BOOL GetIncludeColors();
	void SetIncludeColors(BOOL bNewValue);
	BOOL GetUseSeriesFormat();
	void SetUseSeriesFormat(BOOL bNewValue);
	CString GetValueFormat();
	void SetValueFormat(LPCTSTR lpszNewValue);
	long GetEncoding();
	void SetEncoding(long nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_ODSEXPORT_H__1401FD6C_8323_470E_B8CB_5EC6686C8C1A__INCLUDED_)
