#if !defined(AFX_PARETOFUNCTION_H__68FF34A1_5548_4447_A744_AF06793494F4__INCLUDED_)
#define AFX_PARETOFUNCTION_H__68FF34A1_5548_4447_A744_AF06793494F4__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CParetoFunction wrapper class

class CParetoFunction : public COleDispatchDriver
{
public:
	CParetoFunction() {}		// Calls COleDispatchDriver default constructor
	CParetoFunction(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CParetoFunction(const CParetoFunction& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_PARETOFUNCTION_H__68FF34A1_5548_4447_A744_AF06793494F4__INCLUDED_)
