#if !defined(AFX_PIEANGLE_H__B42A95CE_082D_41B0_88E5_54C032CA3F77__INCLUDED_)
#define AFX_PIEANGLE_H__B42A95CE_082D_41B0_88E5_54C032CA3F77__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CPieAngle wrapper class

class CPieAngle : public COleDispatchDriver
{
public:
	CPieAngle() {}		// Calls COleDispatchDriver default constructor
	CPieAngle(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CPieAngle(const CPieAngle& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	double GetStartAngle();
	void SetStartAngle(double newValue);
	double GetMidAngle();
	void SetMidAngle(double newValue);
	double GetEndAngle();
	void SetEndAngle(double newValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_PIEANGLE_H__B42A95CE_082D_41B0_88E5_54C032CA3F77__INCLUDED_)
