#if !defined(AFX_QTCLUSTERING_H__4C4EE485_A2BC_4126_A1D9_4656577361F1__INCLUDED_)
#define AFX_QTCLUSTERING_H__4C4EE485_A2BC_4126_A1D9_4656577361F1__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CQTClustering wrapper class

class CQTClustering : public COleDispatchDriver
{
public:
	CQTClustering() {}		// Calls COleDispatchDriver default constructor
	CQTClustering(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CQTClustering(const CQTClustering& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetLinkage();
	void SetLinkage(long nNewValue);
	long GetMinCount();
	void SetMinCount(long nNewValue);
	long GetMaxDiameter();
	void SetMaxDiameter(long nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_QTCLUSTERING_H__4C4EE485_A2BC_4126_A1D9_4656577361F1__INCLUDED_)
