#if !defined(AFX_REPAINTMONITORTOOL_H__0645A766_74D5_4724_AB80_EC5DFBB42DCC__INCLUDED_)
#define AFX_REPAINTMONITORTOOL_H__0645A766_74D5_4724_AB80_EC5DFBB42DCC__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CTextShape;
class CAnnotationCallout;
class CTeeSelected;

/////////////////////////////////////////////////////////////////////////////
// CRepaintMonitorTool wrapper class

class CRepaintMonitorTool : public COleDispatchDriver
{
public:
	CRepaintMonitorTool() {}		// Calls COleDispatchDriver default constructor
	CRepaintMonitorTool(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CRepaintMonitorTool(const CRepaintMonitorTool& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetPosition();
	void SetPosition(long nNewValue);
	CTextShape GetShape();
	CString GetText();
	void SetText(LPCTSTR lpszNewValue);
	CAnnotationCallout GetCallout();
	long GetTextAlignment();
	void SetTextAlignment(long nNewValue);
	BOOL Clicked(long X, long Y);
	long GetWidth();
	void SetWidth(long nNewValue);
	long GetHeight();
	void SetHeight(long nNewValue);
	short GetCursor();
	void SetCursor(short nNewValue);
	long GetLeft();
	void SetLeft(long nNewValue);
	long GetTop();
	void SetTop(long nNewValue);
	BOOL GetAutoSize();
	void SetAutoSize(BOOL bNewValue);
	// method 'GetBounds' not emitted because of invalid return type or parameter type
	void SetBounds(long Left, long Top, long Right, long Bottom);
	long GetPositionUnits();
	void SetPositionUnits(long nNewValue);
	CTeeSelected GetSelected();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_REPAINTMONITORTOOL_H__0645A766_74D5_4724_AB80_EC5DFBB42DCC__INCLUDED_)
