#if !defined(AFX_RVIFUNCTION_H__9B40285E_9F9B_4BFC_A9BE_8F9BBDED60B6__INCLUDED_)
#define AFX_RVIFUNCTION_H__9B40285E_9F9B_4BFC_A9BE_8F9BBDED60B6__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CPen1;
class CSeries;

/////////////////////////////////////////////////////////////////////////////
// CRVIFunction wrapper class

class CRVIFunction : public COleDispatchDriver
{
public:
	CRVIFunction() {}		// Calls COleDispatchDriver default constructor
	CRVIFunction(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CRVIFunction(const CRVIFunction& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CPen1 GetSignalPen();
	CSeries GetSignal();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_RVIFUNCTION_H__9B40285E_9F9B_4BFC_A9BE_8F9BBDED60B6__INCLUDED_)
