#if !defined(AFX_SCROLLPAGERTOOL_H__229DF7ED_3F72_46B0_B81A_CC4D2BDDA81B__INCLUDED_)
#define AFX_SCROLLPAGERTOOL_H__229DF7ED_3F72_46B0_B81A_CC4D2BDDA81B__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CColorBandTool;
class CPointer;
class CSubChartChart;
class CSubChartTool;

/////////////////////////////////////////////////////////////////////////////
// CScrollPagerTool wrapper class

class CScrollPagerTool : public COleDispatchDriver
{
public:
	CScrollPagerTool() {}		// Calls COleDispatchDriver default constructor
	CScrollPagerTool(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CScrollPagerTool(const CScrollPagerTool& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	VARIANT GetSeries();
	void SetSeries(const VARIANT& newValue);
	long GetAlign();
	void SetAlign(long nNewValue);
	CColorBandTool GetColorBandTool();
	double GetDivisionRatio();
	void SetDivisionRatio(double newValue);
	CPointer GetEndLinePointer();
	BOOL GetNoLimitDrag();
	void SetNoLimitDrag(BOOL bNewValue);
	unsigned long GetPointerHighlightColor();
	void SetPointerHighlightColor(unsigned long newValue);
	CPointer GetStartLinePointer();
	CSubChartChart GetSubChartTChart();
	CSubChartTool GetSubChartTool();
	void AddSeries(long AIndex);
	void RemoveSeries(long AIndex);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_SCROLLPAGERTOOL_H__229DF7ED_3F72_46B0_B81A_CC4D2BDDA81B__INCLUDED_)
