#if !defined(AFX_SEPIAFILTER_H__3743A93F_D7E4_4692_971C_F33FC56D9B17__INCLUDED_)
#define AFX_SEPIAFILTER_H__3743A93F_D7E4_4692_971C_F33FC56D9B17__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CSepiaFilter wrapper class

class CSepiaFilter : public COleDispatchDriver
{
public:
	CSepiaFilter() {}		// Calls COleDispatchDriver default constructor
	CSepiaFilter(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CSepiaFilter(const CSepiaFilter& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_SEPIAFILTER_H__3743A93F_D7E4_4692_971C_F33FC56D9B17__INCLUDED_)
