#if !defined(AFX_SKEWNESSFUNCTION_H__92DE2221_203E_44CD_90EF_C2CD538FF017__INCLUDED_)
#define AFX_SKEWNESSFUNCTION_H__92DE2221_203E_44CD_90EF_C2CD538FF017__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CSkewnessFunction wrapper class

class CSkewnessFunction : public COleDispatchDriver
{
public:
	CSkewnessFunction() {}		// Calls COleDispatchDriver default constructor
	CSkewnessFunction(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CSkewnessFunction(const CSkewnessFunction& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	BOOL GetComplete();
	void SetComplete(BOOL bNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_SKEWNESSFUNCTION_H__92DE2221_203E_44CD_90EF_C2CD538FF017__INCLUDED_)
