#if !defined(AFX_SOBELFILTER_H__6233AB78_ADB5_46C7_8E0B_61FE52304BC4__INCLUDED_)
#define AFX_SOBELFILTER_H__6233AB78_ADB5_46C7_8E0B_61FE52304BC4__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CSobelFilter wrapper class

class CSobelFilter : public COleDispatchDriver
{
public:
	CSobelFilter() {}		// Calls COleDispatchDriver default constructor
	CSobelFilter(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CSobelFilter(const CSobelFilter& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_SOBELFILTER_H__6233AB78_ADB5_46C7_8E0B_61FE52304BC4__INCLUDED_)
