#if !defined(AFX_SUBCHARTTOOL_H__3BF9A21C_F29F_4C93_9BBD_A25DB9C128A3__INCLUDED_)
#define AFX_SUBCHARTTOOL_H__3BF9A21C_F29F_4C93_9BBD_A25DB9C128A3__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CChartCollection;

/////////////////////////////////////////////////////////////////////////////
// CSubChartTool wrapper class

class CSubChartTool : public COleDispatchDriver
{
public:
	CSubChartTool() {}		// Calls COleDispatchDriver default constructor
	CSubChartTool(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CSubChartTool(const CSubChartTool& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CChartCollection GetCharts();
	short GetCursor();
	void SetCursor(short nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_SUBCHARTTOOL_H__3BF9A21C_F29F_4C93_9BBD_A25DB9C128A3__INCLUDED_)
