#if !defined(AFX_SUBSETTEEFUNCTION_H__50C08325_963C_48C8_AF10_65CC2FAAE256__INCLUDED_)
#define AFX_SUBSETTEEFUNCTION_H__50C08325_963C_48C8_AF10_65CC2FAAE256__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CSubsetTeeFunction wrapper class

class CSubsetTeeFunction : public COleDispatchDriver
{
public:
	CSubsetTeeFunction() {}		// Calls COleDispatchDriver default constructor
	CSubsetTeeFunction(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CSubsetTeeFunction(const CSubsetTeeFunction& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	double GetStartValue();
	void SetStartValue(double newValue);
	double GetEndValue();
	void SetEndValue(double newValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_SUBSETTEEFUNCTION_H__50C08325_963C_48C8_AF10_65CC2FAAE256__INCLUDED_)
