#if !defined(AFX_TEEANIMATION_H__3B0F79B7_4280_4050_B022_7FB6A47B2124__INCLUDED_)
#define AFX_TEEANIMATION_H__3B0F79B7_4280_4050_B022_7FB6A47B2124__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CTeeAnimation wrapper class

class CTeeAnimation : public COleDispatchDriver
{
public:
	CTeeAnimation() {}		// Calls COleDispatchDriver default constructor
	CTeeAnimation(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CTeeAnimation(const CTeeAnimation& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetDuration();
	void SetDuration(long nNewValue);
	BOOL GetEnabled();
	void SetEnabled(BOOL bNewValue);
	BOOL GetInverted();
	void SetInverted(BOOL bNewValue);
	BOOL GetLoop();
	void SetLoop(BOOL bNewValue);
	CTeeAnimation GetParent();
	long GetStartTime();
	void SetStartTime(long nNewValue);
	long GetTiming();
	void SetTiming(long nNewValue);
	long GetTimingStyle();
	void SetTimingStyle(long nNewValue);
	CString GetTitle();
	void SetTitle(LPCTSTR lpszNewValue);
	BOOL GetTwoWay();
	void SetTwoWay(BOOL bNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_TEEANIMATION_H__3B0F79B7_4280_4050_B022_7FB6A47B2124__INCLUDED_)
