#if !defined(AFX_TEEANIMATE_H__68DCCFDC_3573_4944_B81A_89DC60D78A88__INCLUDED_)
#define AFX_TEEANIMATE_H__68DCCFDC_3573_4944_B81A_89DC60D78A88__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CAnimations;

/////////////////////////////////////////////////////////////////////////////
// CTeeAnimate wrapper class

class CTeeAnimate : public COleDispatchDriver
{
public:
	CTeeAnimate() {}		// Calls COleDispatchDriver default constructor
	CTeeAnimate(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CTeeAnimate(const CTeeAnimate& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CAnimations GetAnimations();
	BOOL GetLoop();
	void SetLoop(BOOL bNewValue);
	long GetSpeed();
	void SetSpeed(long nNewValue);
	double GetSpeedFactor();
	void SetSpeedFactor(double newValue);
	long GetState();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_TEEANIMATE_H__68DCCFDC_3573_4944_B81A_89DC60D78A88__INCLUDED_)
