#if !defined(AFX_TEECORNER_H__F9FF1BEA_C771_4BEB_8992_8A9D9E315C4D__INCLUDED_)
#define AFX_TEECORNER_H__F9FF1BEA_C771_4BEB_8992_8A9D9E315C4D__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CTeeCorner wrapper class

class CTeeCorner : public COleDispatchDriver
{
public:
	CTeeCorner() {}		// Calls COleDispatchDriver default constructor
	CTeeCorner(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CTeeCorner(const CTeeCorner& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetStyle();
	void SetStyle(long nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_TEECORNER_H__F9FF1BEA_C771_4BEB_8992_8A9D9E315C4D__INCLUDED_)
