#if !defined(AFX_TEECORNERS_H__54A6F4D5_F2D4_45D0_8772_4F1E14A70B7E__INCLUDED_)
#define AFX_TEECORNERS_H__54A6F4D5_F2D4_45D0_8772_4F1E14A70B7E__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CTeeCorner;

/////////////////////////////////////////////////////////////////////////////
// CTeeCorners wrapper class

class CTeeCorners : public COleDispatchDriver
{
public:
	CTeeCorners() {}		// Calls COleDispatchDriver default constructor
	CTeeCorners(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CTeeCorners(const CTeeCorners& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CTeeCorner GetLeftBottom();
	CTeeCorner GetLeftTop();
	CTeeCorner GetRightBottom();
	CTeeCorner GetRightTop();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_TEECORNERS_H__54A6F4D5_F2D4_45D0_8772_4F1E14A70B7E__INCLUDED_)
