#if !defined(AFX_TEEGDIPLUS_H__E3995593_50E9_4F49_9605_600BBA9897B5__INCLUDED_)
#define AFX_TEEGDIPLUS_H__E3995593_50E9_4F49_9605_600BBA9897B5__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CTeeGDIPlus wrapper class

class CTeeGDIPlus : public COleDispatchDriver
{
public:
	CTeeGDIPlus() {}		// Calls COleDispatchDriver default constructor
	CTeeGDIPlus(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CTeeGDIPlus(const CTeeGDIPlus& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	BOOL GetActive();
	void SetActive(BOOL bNewValue);
	BOOL GetAntialias();
	void SetAntialias(BOOL bNewValue);
	long GetAntiAliasText();
	void SetAntiAliasText(long nNewValue);
	void GDIPlusShutdown();
	long GetScale();
	void SetScale(long nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_TEEGDIPLUS_H__E3995593_50E9_4F49_9605_600BBA9897B5__INCLUDED_)
