#if !defined(AFX_TEEPANNING_H__632D2BF2_1363_48FA_A009_AE9BF6B009A7__INCLUDED_)
#define AFX_TEEPANNING_H__632D2BF2_1363_48FA_A009_AE9BF6B009A7__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CTeePanning wrapper class

class CTeePanning : public COleDispatchDriver
{
public:
	CTeePanning() {}		// Calls COleDispatchDriver default constructor
	CTeePanning(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CTeePanning(const CTeePanning& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	BOOL GetActive();
	void SetActive(BOOL bNewValue);
	BOOL GetInsideBounds();
	void SetInsideBounds(BOOL bNewValue);
	long GetMouseWheel();
	void SetMouseWheel(long nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_TEEPANNING_H__632D2BF2_1363_48FA_A009_AE9BF6B009A7__INCLUDED_)
