#if !defined(AFX_TEESHAPES_H__1D1DE2AA_4E82_46A5_AC6D_FFA38A02A65D__INCLUDED_)
#define AFX_TEESHAPES_H__1D1DE2AA_4E82_46A5_AC6D_FFA38A02A65D__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CTeeShapeItem;

/////////////////////////////////////////////////////////////////////////////
// CTeeShapes wrapper class

class CTeeShapes : public COleDispatchDriver
{
public:
	CTeeShapes() {}		// Calls COleDispatchDriver default constructor
	CTeeShapes(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CTeeShapes(const CTeeShapes& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long Add();
	CTeeShapeItem GetItem(long AIndex);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_TEESHAPES_H__1D1DE2AA_4E82_46A5_AC6D_FFA38A02A65D__INCLUDED_)
