#if !defined(AFX_TEESHAPEITEM_H__3D0DCEEB_4841_4BE7_8C94_C0F916C11DDF__INCLUDED_)
#define AFX_TEESHAPEITEM_H__3D0DCEEB_4841_4BE7_8C94_C0F916C11DDF__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CTeeCustomShape;

/////////////////////////////////////////////////////////////////////////////
// CTeeShapeItem wrapper class

class CTeeShapeItem : public COleDispatchDriver
{
public:
	CTeeShapeItem() {}		// Calls COleDispatchDriver default constructor
	CTeeShapeItem(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CTeeShapeItem(const CTeeShapeItem& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CTeeCustomShape GetShape();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_TEESHAPEITEM_H__3D0DCEEB_4841_4BE7_8C94_C0F916C11DDF__INCLUDED_)
