#if !defined(AFX_TEXTSHAPE_H__76B42DB0_EAAF_46CE_81E3_8C22BECBA3AC__INCLUDED_)
#define AFX_TEXTSHAPE_H__76B42DB0_EAAF_46CE_81E3_8C22BECBA3AC__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CTeeFont;
class CGradient;
class CTeeRect;
class CTeeShadow;
class CPen1;
class CBackImage;
class CTeeEmboss;
class CBrush1;
class CShapeCallout;
class CTeeCorners;
class CTeeShapes;
class CMargins;

/////////////////////////////////////////////////////////////////////////////
// CTextShape wrapper class

class CTextShape : public COleDispatchDriver
{
public:
	CTextShape() {}		// Calls COleDispatchDriver default constructor
	CTextShape(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CTextShape(const CTextShape& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	unsigned long GetColor();
	void SetColor(unsigned long newValue);
	CTeeFont GetFont();
	CGradient GetGradient();
	long GetShadowSize();
	void SetShadowSize(long nNewValue);
	unsigned long GetShadowColor();
	void SetShadowColor(unsigned long newValue);
	BOOL GetTransparent();
	void SetTransparent(BOOL bNewValue);
	long GetShapeStyle();
	void SetShapeStyle(long nNewValue);
	long GetTransparency();
	void SetTransparency(long nNewValue);
	CTeeRect GetShapeBounds();
	long GetBevel();
	void SetBevel(long nNewValue);
	long GetBevelWidth();
	void SetBevelWidth(long nNewValue);
	void ShowEditorShape(BOOL HideTexts, LPCTSTR Caption);
	CTeeShadow GetShadow();
	long GetRoundSize();
	void SetRoundSize(long nNewValue);
	CPen1 GetPen();
	CBackImage GetPicture();
	void Show();
	void Hide();
	CTeeEmboss GetEmboss();
	long GetWidth();
	void SetWidth(long nNewValue);
	long GetHeight();
	void SetHeight(long nNewValue);
	CPen1 GetFrame();
	CBrush1 GetBrush();
	CShapeCallout GetShapeCallout();
	CTeeCorners GetCorners();
	CTeeShapes GetChildren();
	long GetChildLayout();
	void SetChildLayout(long nNewValue);
	long GetAngle();
	void SetAngle(long nNewValue);
	BOOL GetShapeVisible();
	void SetShapeVisible(BOOL bNewValue);
	long GetTextFormat();
	void SetTextFormat(long nNewValue);
	BOOL GetCustomPosition();
	void SetCustomPosition(BOOL bNewValue);
	long GetLeft();
	void SetLeft(long nNewValue);
	long GetTop();
	void SetTop(long nNewValue);
	BOOL GetAutoSize();
	void SetAutoSize(BOOL bNewValue);
	BOOL GetClipText();
	void SetClipText(BOOL bNewValue);
	short GetCursor();
	void SetCursor(short nNewValue);
	CString GetText();
	void SetText(LPCTSTR lpszNewValue);
	long GetTextAlignment();
	void SetTextAlignment(long nNewValue);
	CMargins GetMargins();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_TEXTSHAPE_H__76B42DB0_EAAF_46CE_81E3_8C22BECBA3AC__INCLUDED_)
