#if !defined(AFX_THEMESLIST_H__46EC8A86_8831_42B4_AFE8_EAEB35D2F1CD__INCLUDED_)
#define AFX_THEMESLIST_H__46EC8A86_8831_42B4_AFE8_EAEB35D2F1CD__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CThemesList wrapper class

class CThemesList : public COleDispatchDriver
{
public:
	CThemesList() {}		// Calls COleDispatchDriver default constructor
	CThemesList(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CThemesList(const CThemesList& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	void ApplyFromChartLink(long Chart);
	void ApplyFromTee(LPCTSTR FileName);
	void ApplyFromChartLinkx64(const VARIANT& Chartx64);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_THEMESLIST_H__46EC8A86_8831_42B4_AFE8_EAEB35D2F1CD__INCLUDED_)
