#if !defined(AFX_TRENDFUNCTION_H__365B4471_6FA3_4E1A_90B1_34D39BA92970__INCLUDED_)
#define AFX_TRENDFUNCTION_H__365B4471_6FA3_4E1A_90B1_34D39BA92970__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CTrendFunction wrapper class

class CTrendFunction : public COleDispatchDriver
{
public:
	CTrendFunction() {}		// Calls COleDispatchDriver default constructor
	CTrendFunction(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CTrendFunction(const CTrendFunction& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long CalculateTrend(double* m, double* b, long SourceSeriesIndex, long FirstIndex, long LastIndex);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_TRENDFUNCTION_H__365B4471_6FA3_4E1A_90B1_34D39BA92970__INCLUDED_)
