#if !defined(AFX_WORLDFLAGS_H__8F7F72CC_CAF4_4F33_B2FF_77346AED507E__INCLUDED_)
#define AFX_WORLDFLAGS_H__8F7F72CC_CAF4_4F33_B2FF_77346AED507E__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CWorldFlags wrapper class

class CWorldFlags : public COleDispatchDriver
{
public:
	CWorldFlags() {}		// Calls COleDispatchDriver default constructor
	CWorldFlags(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CWorldFlags(const CWorldFlags& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	BOOL GetVisible();
	void SetVisible(BOOL bNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_WORLDFLAGS_H__8F7F72CC_CAF4_4F33_B2FF_77346AED507E__INCLUDED_)
