/* DO NOT EDIT THIS FILE - it is machine generated */

/* Header for class com_zolix_math_Math4JNI */

#ifndef _Included_STDAFX_H
#define _Included_STDAFX_H
#ifdef __cplusplus
extern "C" {
#endif
	__declspec(dllexport)bool baseline_correct(double* dIn,int nInSize,double nNUMber,double* result,int* nResultSize);

	__declspec(dllexport)bool cal_peak_area(double* dIn, int nInSize,double mode,double* FWHM_data,int* FWHM_size);

	__declspec(dllexport)bool denoise2(double* dIn,int nInSize,double nNUMber,double* result,int* nResultSize);

	__declspec(dllexport)bool halfwidth(double* dIn, int nInSize,double* FWHM_data,int* FWHM_size);
#ifdef __cplusplus
} 
#endif
#endif
