
; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "INScan-Lite"
#define MyAppVersion "23.07.24"
#define MyAppPublisher "Zolix, Inc."
#define MyAppExeName "INScan-Lite.exe"
#define OutputDir "E:\wangkai\FI-PC\Setup\Output"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={#MyAppPublisher} {#MyAppName} {#MyAppVersion}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\Zolix\{#MyAppName}
DefaultGroupName=INScan-Lite
AllowNoIcons=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
PrivilegesRequired=admin
;PrivilegesRequiredOverridesAllowed=dialog
OutputDir={#OutputDir}
OutputBaseFilename={#MyAppName} V{#MyAppVersion}
SetupIconFile=E:\wangkai\FI-PC\INScan-Lite\res\INScan-Lite.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern
UninstallDisplayIcon=E:\wangkai\FI-PC\INScan-Lite\res\INScan-Lite.ico


[Registry]
Root: HKLM64; Subkey: Software\{#MyAppPublisher}; Check: IsWin64; ValueType: string; ValueName: INScan-Lite; ValueData: {#MyAppVersion}; Flags: uninsdeletekey
Root: HKLM; Subkey: Software\{#MyAppPublisher}; Check: not IsWin64; ValueType: string; ValueName: INScan-Lite; ValueData: {#MyAppVersion}; Flags: uninsdeletekey

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "chinesesimplified"; MessagesFile: "compiler:Languages\ChineseSimplified.isl"
;Name: "chinesetraditional"; MessagesFile: "compiler:Languages\ChineseTraditional.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; 

[Files]
Source: "E:\wangkai\FI-PC\Release\*"; DestDir: "{app}"; Flags: ignoreversion; Components: main; BeforeInstall: ChangeDisplay;
Source: "E:\wangkai\FI-PC\Release\LANGUAGE\*"; DestDir: "{app}\LANGUAGE"; Flags: ignoreversion
Source: "E:\wangkai\FI-PC\Release\res\*"; DestDir: "{app}\res"; Flags: ignoreversion
;Source: "F:\workplace\ZolixDLL\INScan-JC\ocx\*"; DestDir: "{sys}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "E:\wangkai\FI-PC\Driver\*"; DestDir: "{app}\Driver"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "E:\wangkai\FI-PC\VC\*"; DestDir: "{app}\VC"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "E:\wangkai\FI-PC\Prior\*"; DestDir: "{app}\Prior"; Flags: ignoreversion recursesubdirs createallsubdirs

; NOTE: Don't use "Flags: ignoreversion" on any shared system files

;Source: "E:\wangkai\FI-PC\INScan-LiteC.ini"; DestName: "INScan-Lite.ini"; DestDir: "{app}"; Languages: english; 
Source: "E:\wangkai\FI-PC\INScan-LiteC.ini"; DestName: "INScan-Lite.ini"; DestDir: "{app}"; Languages: chinesesimplified; 
;Source: "E:\wangkai\FI-PC\INScan-LiteNoLogo-AddPoint250.ini"; DestName: "INScan-Lite.ini"; DestDir: "{app}"; Languages: chinesesimplified; 
;Source: "F:\workplace\ZolixDLL\INScan-Lite\INScan-LiteT.ini"; DestName: "INScan-Lite.ini"; DestDir: "{app}"; Languages: chinesetraditional; 

;Source: "F:\自动对焦\INScan-JC\INScan-JC\ocx\TeeChart2011.ocx"; DestDir: "{sys}";Flags: restartreplace  regserver; 
;Source: "F:\自动对焦\INScan-JC\INScan-JC\ocx\ZolixCurveProcessing.ocx"; DestDir: "{sys}"; Flags: restartreplace  regserver; 
;Source: "F:\自动对焦\INScan-JC\INScan-JC\ocx\ZLanguage.ocx"; DestDir: "{sys}";Flags: restartreplace  regserver; 

Source: "E:\wangkai\FI-PC\VC\*"; DestDir: "{app}\VC\"; Flags: ignoreversion; Components: vclibs\vclib1; BeforeInstall: MyBeforInstall('{app}\VC\MSVBCRT.exe');

Source: "E:\wangkai\FI-PC\ocx\*.ocx"; DestDir: "{sys}";Flags: restartreplace regserver; Components: activeX; BeforeInstall: ChangeDisplay

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; 
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Components]
Name: main; Description: INScan-Lite V{#MyAppVersion}; Types: full;
Name: activeX; Description: ActiveX; Types: full;
Name: "vclibs"; Description: "VC Runtime Lib"; Types: full
Name: vclibs\vclib1; Description: MSVBCRT; Types: full;

[Code] 
var
DetailList: TNewListBox;
newFileNameLabel: TNewStaticText;
LastDir: string;
lan: String;
OutputDir: String;
Extracting: String;

function GetInstalledVersion(): String;
var
  InstalledVersion: String;

begin
  InstalledVersion :='';
  if IsWin64 then begin
    RegQueryStringValue(HKLM64, 'Software\Zolix', 'INScan-Lite', InstalledVersion);
  end else begin
    RegQueryStringValue(HKLM, 'Software\Zolix', 'INScan-Lite', InstalledVersion);
  end;

  Result := InstalledVersion;
end;


procedure MyBeforInstall(file: String);
var
  ResultCode: Integer;

begin
  Exec(ExpandConstant(file), '', '', SW_SHOWNORMAL,ewWaitUntilTerminated, ResultCode);
end;


function isEnglishLan(): Boolean;
begin
  result := true;
  if lan = 'English' then begin
    result := true;
  end;
   
  if lan = 'Chinese' then begin
    result := false;
  end; 
end;

function InitializeSetup(): Boolean;
var
PrevVer: String;
Selected: Integer;

begin
  lan := ActiveLanguage;
  
  result := true;
  PrevVer := GetInstalledVersion();

  if length(PrevVer) > 0 then begin//已安装，先卸载
    if lan = 'English' then begin
      OutputDir := 'OutputDir: ';
      Extracting := 'Extracting: ';
      Selected := MsgBox('This program has already been installed, continue to install ?', mbError,MB_YESNO);
    end;
     
    if lan = 'Chinese' then begin
      OutputDir := '输出目录: '
      Extracting := '正在提取: '
      Selected := MsgBox('此程序已安装，是否继续 ?', mbError,MB_YESNO);
    end;
    result := (Selected = IDYES);
  end;

  
end;

procedure InitializeWizard();
begin
  DetailList:= TNewListBox.Create(WizardForm);
  DetailList.Parent := WizardForm.InstallingPage;
  DetailList.Left := ScaleX(0);
  DetailList.Top := ScaleY(70);
  DetailList.Width := ScaleX(417);
  DetailList.Height := ScaleY(153);
  newFileNameLabel:= TNewStaticText.Create(WizardForm)      // 创建 FileNameLabel 的替代
  newFileNameLabel.Parent := WizardForm.InstallingPage;
  newFileNameLabel.Top := WizardForm.FileNameLabel.Top;
  newFileNameLabel.Left := WizardForm.FileNameLabel.Left;
  newFileNameLabel.Width := WizardForm.FileNameLabel.Width;
  WizardForm.FileNameLabel.Visible := false;               // 隐藏本来的 FileNameLabel

  LastDir:= '';
end;

procedure ChangeDisplay;
var
  dn, fn: string;
  pct: Extended;
begin
  pct := (WizardForm.ProgressGauge.Position-WizardForm.ProgressGauge.Min)/(WizardForm.ProgressGauge.Max-WizardForm.ProgressGauge.Min)*100;
  dn:= ExpandConstant(ExtractFileDir(CurrentFileName));
  fn:= ExtractFileName(CurrentFileName);

  WizardForm.StatusLabel.Caption:= OutputDir + dn;
  newFileNameLabel.Caption:= Extracting + fn;
  if dn <> LastDir then
    begin
      DetailList.Items.Append(OutputDir + dn);
      LastDir:= dn;
    end;
  DetailList.Items.Append(Extracting + fn);
  DetailList.ItemIndex := DetailList.Items.Count - 1;
end;


[UninstallRun]

Filename: "regsvr32"; Parameters:"/u /s TeeChart2011.ocx" 
Filename: "regsvr32"; Parameters:"/u /s ZolixCurveProcessing.ocx"
Filename: "regsvr32"; Parameters:"/u /s ZLanguage.ocx"
[UninstallDelete]
Type: files; Name:"{sys}//TeeChart2011.ocx"
Type: files; Name:"{sys}//ZolixCurveProcessing.ocx"
Type: files; Name:"{sys}//ZLanguage.ocx"